#!/bin/bash
set -ue

: "${DOCKER_TAG:=ftl-sdk}"

main () {
  echo "running linter"

  local lint_script;
  lint_script="$(dirname "$(realpath -s "$0")")/lint"
  "${lint_script}"

  echo "running stream test"
  docker run \
    --rm \
    -e MIXER_STREAMER_KEY \
    -e CHANNEL \
    -e INGEST \
    -e FPS \
    --entrypoint ./scripts/test \
    "$DOCKER_TAG"
}

main

